services:
  azure-storage:
      image: mcr.microsoft.com/azure-storage/azurite:latest
      container_name: azure-storage
      volumes:
        - c:/azurite:/data
      ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"